version: '3.3'

networks:
  metric-monitoring:
    driver: bridge
  logs-monitoring: 
    driver: bridge

volumes:
  prometheus: {}
  alertmanager: {}
  influxdb: {}

services:
  # NGINX SERVER
  nginx:
    image: nginx
    container_name: nginx
    ports: ["82:80", "83:8000"]
    environment:
      - NGINX_HOST=qt
      - NGINX_PORT=80
    volumes:
      - $PWD/config/nginx/server-status.conf:/etc/nginx/conf.d/server-status.conf:ro
    networks:
      - metric-monitoring
      - logs-monitoring
  # NGINX SERVER EXPORTER FOR CONTAINER
  nginx_exporter_container:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter_container
    ports: ["9113:9113"]
    command: 
      - --nginx.scrape-uri=http://nginx:8000
    networks:
      - metric-monitoring
  # NGINX SERVER EXPORTER FOR HOST MACHINE
  nginx_exporter_host:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter_host
    ports: ["9114:9113"]
    command: 
      - --nginx.scrape-uri=http://host.docker.internal:8002/server-status
    networks:
      - metric-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # INFLUXDB FOR TELEGRAF
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports: ["8086:8086"]
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: root1234
      DOCKER_INFLUXDB_INIT_ORG: qt
      DOCKER_INFLUXDB_INIT_BUCKET: default
    networks:
      - metric-monitoring
  # APACHE SERVER
  httpd:
    image: httpd
    container_name: httpd
    ports: ["81:80"]
    volumes:
      - $PWD/config/apache/httpd-info.conf:/usr/local/apache2/conf/extra/httpd-info.conf:ro
      - $PWD/config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - metric-monitoring
      - logs-monitoring
  # APACHE SERVER EXPORTER FOR CONTAINER
  apache_exporter_container:
    image: bitnami/apache-exporter:latest
    container_name: apache_exporter_container
    privileged: true
    restart: unless-stopped
    ports: ['9117:9117']
    entrypoint: /bin/apache_exporter --scrape_uri="http://httpd/server-status?auto"
    networks:
      - metric-monitoring
  # APACHE SERVER EXPORTER FOR HOST MACHINE
  apache_exporter_host:
    image: bitnami/apache-exporter:latest
    container_name: apache_exporter_host
    privileged: true
    restart: unless-stopped
    ports: ['9118:9117']
    entrypoint: /bin/apache_exporter --scrape_uri="http://host.docker.internal:8001/server-status?auto"
    networks:
      - metric-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # NODE EXPORTER
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - metric-monitoring
  # REDIS
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 9100
    networks:
      - metric-monitoring
  # CADVISOR
  cadvisor:
    depends_on:
      - redis
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - metric-monitoring
  # ALERT MANAGER
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager/:/config/
      - alertmanager:/data/
    command: --config.file=/config/alertmanager.yaml --log.level=debug
    networks:
      - metric-monitoring
      - logs-monitoring
  # PROMETHEUS
  prometheus:
    depends_on:
      - cadvisor
      - node-exporter
      - alertmanager
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - metric-monitoring
  # LOKI
  loki:
    depends_on:
      - alertmanager
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./config/loki/:/etc/loki/
    command: -config.file=/etc/loki/loki-config.yaml
    expose:
      - 3100
    networks:
      - logs-monitoring
  # PROMTAIL
  promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config/promtail/:/etc/promtail/
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - logs-monitoring
  # GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./config/grafana/providers:/etc/grafana/provisioning/dashboards
      - ./config/grafana/configs:/etc/grafana-config
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "3000:3000"
    networks:
      - metric-monitoring
      - logs-monitoring
