apiVersion: 1

datasources:
- name: Loki
  type: loki
  url: http://loki:3100
  editable: false
  isDefault: false
  uid: loki-datasource
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  editable: false
  isDefault: false
  uid: prometheus-datasource
